version: '3.8'

services:
  mongodb:
    image: mongo:8.0
    container_name: mongodb
    ports:
      - ${MONGODB_PORT}:27017
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./docker/volumes/mongodb:/data/db